name: Test

on:
  push:
    branches: [ main, cline ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-4-dev gobject-introspection libgirepository1.0-dev
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-xvfb
        pip install -e .
    
    - name: Run backend tests
      run: |
        pytest tests/ -v -m "not frontend"
    
    - name: Run frontend tests with Xvfb
      run: |
        xvfb-run --auto-servernum pytest tests/ -v -m "frontend"
    
    - name: Generate coverage report
      run: |
        pytest --cov=toshy tests/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
